name: UMC Gradle Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-java@v5
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: keyscan
      run: mkdir -p ~/.ssh/ && ssh-keyscan -t rsa teamopenindustry.cc >> ~/.ssh/known_hosts
    - name: Gradle Publish
      env:
       MAVENCI_PASS: ${{ secrets.MAVENCI_PASS }}
      run: ./gradlew publish
    - uses: actions/upload-artifact@v6
      with:
        name: UMCSetup
        path: build/libs/UMCSetup.jar
